version: "3.8"

services:

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=produtos
      - POSTGRES_USER=produtos
      - POSTGRES_DB=produtos-db
    ports:
      - 5432:5432

  service-discovery:
    image: service-discovery:1.0-SNAPSHOT
    ports:
      - 8761:8761

  produtos:
    image: produtos:1.0-SNAPSHOT
    ports:
      - 8080:8080
    environment:
      - PRODUTO_DB_HOST=database
      - PRODUTO_DB_PORT=5432
      - PRODUTO_DB_USER=produtos
      - PRODUTO_DB_PASSWORD=produtos
      - EUREKA_SERVER_HOST=eureka
      - EUREKA_SERVER_PORT=8761
    links:
      - "db:database"
      - "service-discovery:eureka"
    depends_on:
      - db
      - service-discovery
    restart: on-failure

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    links:
      - "produtos:produtos"

  grafana:
    image: grafana/grafana
    ports:
      - 3001:3000