version: "3.8"

services:

  db_keycloak:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_DB=keycloak
    ports:
      - 5433:5432

  db_produto:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=produtos
      - POSTGRES_USER=produtos
      - POSTGRES_DB=produtos-db
    ports:
      - 5434:5432

  db_comanda:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=comandas
      - POSTGRES_USER=comandas
      - POSTGRES_DB=comandas-db
    ports:
      - 5435:5432

  keycloak:
    image: jboss/keycloak:latest
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: db_keycloak
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PORT: 5432
      DB_SCHEMA: public
      DB_PASSWORD: keycloak
      KEYCLOAK_USER: root
      KEYCLOAK_PASSWORD: root
      KEYCLOAK_IMPORT: /tmp/restaurante_realm.json
    ports:
      - 8080:8080
    volumes:
      - ./keycloak/imports/restaurante_realm.json:/tmp/restaurante_realm.json
    depends_on:
      - db_keycloak

  admin-server:
    image: admin-server:1.0-SNAPSHOT
    ports:
      - 8081:8080

  service-discovery:
    image: service-discovery:1.0-SNAPSHOT
    ports:
      - 8761:8761

  zipkinserver:
    image: openzipkin/zipkin:latest
    ports:
    - 9411:9411

  produtos:
    image: produtos:1.0-SNAPSHOT
    ports:
      - 8082:8080
    environment:
      - PRODUTO_DB_HOST=database
      - PRODUTO_DB_PORT=5432
      - PRODUTO_DB_USER=produtos
      - PRODUTO_DB_PASSWORD=produtos
      - EUREKA_SERVER_HOST=eureka
      - EUREKA_SERVER_PORT=8761
      - ADMIN_SERVER_HOST=admin
      - ADMIN_SERVER_PORT=8080
      - SEC_HOST=keycloak
      - SEC_PORT=8080
      - SEC_REALM=restaurante
      - ZIPKIN_HOST=zipkinserver
      - ZIPKIN_PORT=9411
    links:
      - "db_produto:database"
      - "service-discovery:eureka"
      - "admin-server:admin"
      - "keycloak:keycloak"
    depends_on:
      - keycloak
      - db_produto
      - admin-server
      - service-discovery
      - zipkinserver
    restart: on-failure

  comandas:
    image: comandas:1.0-SNAPSHOT
    ports:
      - 8083:8080
    environment:
      - COMANDA_DB_HOST=database
      - COMANDA_DB_PORT=5432
      - COMANDA_DB_USER=comandas
      - COMANDA_DB_PASSWORD=comandas
      - EUREKA_SERVER_HOST=eureka
      - EUREKA_SERVER_PORT=8761
      - ADMIN_SERVER_HOST=admin
      - ADMIN_SERVER_PORT=8080
      - SEC_HOST=keycloak
      - SEC_PORT=8080
      - SEC_REALM=restaurante
      - ZIPKIN_HOST=zipkinserver
      - ZIPKIN_PORT=9411
    links:
      - "db_comanda:database"
      - "service-discovery:eureka"
      - "admin-server:admin"
    depends_on:
      - db_comanda
      - admin-server
      - service-discovery
      - zipkinserver
    restart: on-failure

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    links:
      - "produtos:produtos"
      - "comandas:comandas"

  grafana:
    image: grafana/grafana
    ports:
      - 3001:3000
    depends_on:
      - prometheus