version: "3.8"

services:

  db_produto:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=produtos
      - POSTGRES_USER=produtos
      - POSTGRES_DB=produtos-db
    ports:
      - 5432:5432

  db_comanda:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=comandas
      - POSTGRES_USER=comandas
      - POSTGRES_DB=comandas-db
    ports:
      - 5433:5432

  admin-server:
    image: admin-server:1.0-SNAPSHOT
    ports:
      - 8182:8080

  service-discovery:
    image: service-discovery:1.0-SNAPSHOT
    ports:
      - 8761:8761

  produtos:
    image: produtos:1.0-SNAPSHOT
    ports:
      - 8080:8080
    environment:
      - PRODUTO_DB_HOST=database
      - PRODUTO_DB_PORT=5432
      - PRODUTO_DB_USER=produtos
      - PRODUTO_DB_PASSWORD=produtos
      - EUREKA_SERVER_HOST=eureka
      - EUREKA_SERVER_PORT=8761
      - ADMIN_SERVER_HOST=admin
      - ADMIN_SERVER_PORT=8080
    links:
      - "db_produto:database"
      - "service-discovery:eureka"
      - "admin-server:admin"
    depends_on:
      - db_produto
      - admin-server
      - service-discovery
    restart: on-failure

  comandas:
    image: comandas:1.0-SNAPSHOT
    ports:
      - 8081:8080
    environment:
      - COMANDA_DB_HOST=database
      - COMANDA_DB_PORT=5432
      - COMANDA_DB_USER=comandas
      - COMANDA_DB_PASSWORD=comandas
      - EUREKA_SERVER_HOST=eureka
      - EUREKA_SERVER_PORT=8761
      - ADMIN_SERVER_HOST=admin
      - ADMIN_SERVER_PORT=8080
    links:
      - "db_comanda:database"
      - "service-discovery:eureka"
      - "admin-server:admin"
    depends_on:
      - db_comanda
      - admin-server
      - service-discovery
    restart: on-failure

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    links:
      - "produtos:produtos"
      - "comandas:comandas"

  grafana:
    image: grafana/grafana
    ports:
      - 3001:3000
    depends_on:
      - prometheus