server:
  port: 8080
  servlet:
    context-path: /api-produto
spring:
  application:
    name: produtos
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    auto-commit: false
  data:
    jpa:
      repositories:
        enabled: true

---

spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: SA
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    database: h2
  flyway:
    enabled: false
eureka:
  client:
    enabled: false

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://${PRODUTO_DB_HOST}:${PRODUTO_DB_PORT}/produtos-db
    username: ${PRODUTO_DB_USER}
    password: ${PRODUTO_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    url: jdbc:postgresql://${PRODUTO_DB_HOST}:${PRODUTO_DB_PORT}/produtos-db
    user: ${PRODUTO_DB_USER}
    password: ${PRODUTO_DB_PASSWORD}
  boot:
    admin:
      client:
        url: http://${ADMIN_SERVER_HOST}:${ADMIN_SERVER_PORT}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${SEC_HOST}:${SEC_PORT}/auth/realms/${SEC_REALM}
          jwk-set-uri: http://${SEC_HOST}:${SEC_PORT}/auth/realms/${SEC_REALM}/protocol/openid-connect/certs
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

server:
  tomcat:
    mbeanregistry:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_HOST}:${EUREKA_SERVER_PORT}/eureka
    fetch-registry: true